### ISSUE TITLE
Reboot of the project?

### ISSUE THREAD

**Issue by patlecat** [Laravel-Philippines/LaravelPH-Website#15]
In the fb group someone announced that a relaunch or rather reboot of this project is en route. Please inform us when that happens so people can start contributing.

We need a list of requirements first though and a roadmap.

**Comment by rmrhz** [comment]
Coordinate with @aindong & @jpalala for this matter

**Comment by patlecat** [comment]
I prefer they make an official announcement here before. Then I would be inclined to engage.

**Comment by aindong** [comment]
hi @patlecat the project has been rebooted a lot of times since most of the people volunteered but didn't had the chance to really `contribute` something and the project got pending a lot of times. We know because we are also doing our full time job. I think this is the very first project 3 years ago? Right now we don't have a roadmap yet, but we are getting there. We just re-started the core contributors and we'll promise to give you some news about it. Thank you so much for your willingness to contribute.

**Comment by jpalala** [comment]
Road map is the jobs na lang and blog if ever people would blog about Laravel or talk about their companies. Un lang

**Comment by patlecat** [comment]
Let's start with something small and simple that let's people contribute to the site and getting used to come to the site. Then it will be surely easier to motivate ppl to do more.

So what could be the most basic content and service to offer at first? A blog? A forum (like described on Laracasts)?

**Comment by aprilmintacpineda** [comment]
We can recreate the project using laravel 5.4 with modern front-end technologies that can handle wide range of complexity like the react-redux-saga combo.

**Comment by patlecat** [comment]
Nah, 5.5 LTS is around the corner. That should be the weapon of choice here! But when will this reboot for good?
